### ISSUE TITLE
Fatal error: Allowed memory size of X bytes exhausted

### ISSUE THREAD

**Issue by fschoenfeldt** [iBobik/drupal-composer-docker#5]
.. when running `composer create-project drupal-composer/drupal-project:8.x-dev . --stability dev --no-interaction` inside the container, it throws this error:
![image](https://user-images.githubusercontent.com/4721311/96849123-8325cb80-1455-11eb-9b20-5df921b85414.png)

I already tried increasing the memory limit of the docker app to 8GB which should be more than enough.

**Comment by fschoenfeldt** [comment]
I'd like to add a note to the installation instructions, that you should just prepend `COMPOSER_MEMORY_LIMIT=-1` to the installation command. I found the resolution [here](https://travis-ci.community/t/composer-install-during-docker-image-build-allowed-memory-size-exhausted/7084/3)

**Comment by iBobik** [comment]
This is eternal issue of the Composer:

https://github.com/composer/composer/issues/8063
